# Usa uma imagem leve do Linux (Alpine)
FROM alpine:latest

# Comando que será executado quando o contentor iniciar
ENTRYPOINT ["echo", "Olá! Esta mensagem vem de dentro do contentor Docker da minha ação personalizada."]
